// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;

namespace Zoo.Infrastructure.Entities.Zoo
{
    public class AnimalEatConfiguration : IEntityTypeConfiguration<AnimalEat>
    {
        public void Configure(EntityTypeBuilder<AnimalEat> entity)
        {
            entity.HasKey(e => new { e.AnimalId, e.FoodId });

            entity.HasOne(d => d.Animal)
                .WithMany(p => p.AnimalEats)
                .HasForeignKey(d => d.AnimalId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_AnimalEats_Animal");

            entity.HasOne(d => d.Food)
                .WithMany(p => p.AnimalEats)
                .HasForeignKey(d => d.FoodId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_AnimalEats_Food");
        }
    }
}
