// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Zoo.Infrastructure.Entities.Zoo
{
    public partial class Animal
    {
        public Animal()
        {
            AnimalEats = new HashSet<AnimalEat>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public int Legs { get; set; }
        public int FamilyId { get; set; }

        public virtual Family Family { get; set; }
        public virtual ICollection<AnimalEat> AnimalEats { get; set; }
    }
}