// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Zoo.Infrastructure.Entities.Zoo
{
    public partial class Classification
    {
        public Classification()
        {
            Families = new HashSet<Family>();
        }

        public int Id { get; set; }
        public string Name { get; set; }

        public virtual ICollection<Family> Families { get; set; }
    }
}