// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Zoo.Infrastructure.Entities.Zoo
{
    public partial class Family
    {
        public Family()
        {
            AnimalCanEats = new HashSet<AnimalCanEat>();
            Animals = new HashSet<Animal>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public int ClassificationId { get; set; }

        public virtual Classification Classification { get; set; }
        public virtual ICollection<AnimalCanEat> AnimalCanEats { get; set; }
        public virtual ICollection<Animal> Animals { get; set; }
    }
}