// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

#nullable disable

namespace Zoo.Infrastructure.Entities.Zoo
{
    public partial class ZooContext : DbContext
    {
        public ZooContext(DbContextOptions<ZooContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Animal> Animals { get; set; }
        public virtual DbSet<AnimalCanEat> AnimalCanEats { get; set; }
        public virtual DbSet<AnimalEat> AnimalEats { get; set; }
        public virtual DbSet<Classification> Classifications { get; set; }
        public virtual DbSet<Family> Families { get; set; }
        public virtual DbSet<Food> Foods { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.ApplyConfiguration(new AnimalConfiguration());
            modelBuilder.ApplyConfiguration(new AnimalCanEatConfiguration());
            modelBuilder.ApplyConfiguration(new AnimalEatConfiguration());
            modelBuilder.ApplyConfiguration(new ClassificationConfiguration());
            modelBuilder.ApplyConfiguration(new FamilyConfiguration());
            modelBuilder.ApplyConfiguration(new FoodConfiguration());

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}
